### PR TITLE
I think jars from implementation dependencies should not be packaged into ext. Fixed this

### PR DESCRIPTION
**Pull request by guai**

### CODE REVIEW

**Comment by radimk** [comment]
I'm ready to merge this when we fix snapshot dependency.

**Comment by guai** [comment]
There are nb harness 8.1 release in maven central. I'm using this plugin only with 8+ netbeans and am not sure if it will be ok to use harness 8 for building netbeans modules for nb 7.
I changed version in my fork only for that reason. Version shift is not mandatory for implementation deps feature I think.
If you have info about using harness 8 for building for nb 7 then I think we should use harness 8.1 release dep, or else we should revert to 7.4

**Comment by radimk** [comment]
Bits from 8.1 release would be OK. We can drop support for 7.x releases if there is a problem (though I do not expect a problem there).

**Comment by guai** [comment]
harness 8.1 is there now

**Comment by guai** [comment]
New osgi bundle dependencies feature

**Comment by radimk** [comment]
Thanks for the patches!

**Pull request merged**
