### PR TITLE
double star package export in manifest fixed

### PR DESCRIPTION
**Pull request by guai**

### CODE REVIEW

**Comment by radimk** [comment]
can we add a test for this?

**Comment by guai** [comment]
for a one line change in a method that have three lines total?

**Comment by radimk** [comment]
Yes. I suppose you want to preserve this functionality after next patch, right?

**Comment by guai** [comment]
I need double stars in any way. Not sure if this is the ultimate best decision. Before this auto adding a star when omitted was introduced everything was fine too. I can always grep my code

**Comment by guai** [comment]
Actually maven does it differently. one star in cfg means two in manifest and no stars in cfg means one in manifest
I liked it better when there was no transformations here. It's simple and straightforward

**Comment by kelemen** [comment]
I didn't know about the ".**" possibility. However, I would find it slightly tedious if you had to write ".*" for every packages. Anyway, it should be rather easy to add tests to `ManifestGenerationTest`.

**Comment by guai** [comment]
I've added a test

**Pull request merged**
